#********** Driver Parameters ************

provider_can/driver/baudrate: 125
provider_can/driver/device_id: 1
provider_can/driver/unique_id: 1
provider_can/driver/channel: 0
provider_can/driver/usb_device: "KVaser"

#********** Devices parameters ***********

# barometer
provider_can/barometer/enable: true

# bottom light
provider_can/bottom_light/enable: true

# diver interface
provider_can/diver_interface/enable: true

# droppers
provider_can/droppers/enable: true

# grabber
provider_can/grabber/enable: true

# hydrophones
provider_can/hydrophones/enable: true
provider_can/hydrophones/hydro_enable: 0
provider_can/hydrophones/wave_enable: 0
provider_can/hydrophones/pinger_freq: 14 # This is an arbitrary value set in hydrphones code representing a specific freq (5 or 16 = 13000Hz), (6 or 17 = 15000Hz), (7 or 18 = 22000Hz), (8 or 19 = 23000Hz), (9 or 20 = 24000Hz), (10 or 21 = 25000Hz), (11 or 22 = 26000Hz), (12 or 23 = 27000Hz), (13 or 24 = 28000Hz), (14 or 25 = 29000Hz), (15 or 26 = 30000Hz).
provider_can/hydrophones/gain: 4
provider_can/hydrophones/acq_threshold: 1124800758
provider_can/hydrophones/filter_threshold: 15
provider_can/hydrophones/continuous_filter_freq: 5
provider_can/hydrophones/sample_count: 256
provider_can/hydrophones/acq_thrs_mode: 1
provider_can/hydrophones/phase_calc_alg: 0
provider_can/hydrophones/set_cutoff_freq: 24
provider_can/hydrophones/set_preamp_gain: 1
provider_can/hydrophones/fft_enable: 1
provider_can/hydrophones/fft_threshold: 38000
provider_can/hydrophones/fft_prefilter: 1
provider_can/hydrophones/fft_prefilter_type: 5
provider_can/hydrophones/fft_bandwidth: 1
provider_can/hydrophones/fft_trig_mode_Param: 1

# led indicator
provider_can/led_indicator/enable: true

# mission switch
provider_can/mission_switch/enable: true

# power supply
provider_can/power_supply/enable: true
provider_can/power_supply/actuator_bus_state: true
provider_can/power_supply/dvl_state: true
provider_can/power_supply/light_state: true
provider_can/power_supply/motor_bus1_state: true
provider_can/power_supply/motor_bus2_state: true
provider_can/power_supply/motor_bus3_state: true
provider_can/power_supply/pc_state: true
provider_can/power_supply/volt_bus1_state: true
provider_can/power_supply/volt_bus2_state: true

# thrusters
provider_can/thruster_starboard/enable: true
provider_can/thruster_port/enable: true
provider_can/thruster_back_depth/enable: true
provider_can/torpedo_launcher/enable: true
provider_can/thruster_front_depth/enable: true
provider_can/thruster_back_head/enable: true
provider_can/thruster_front_head/enable: true

