#********** Driver Parameters ************

provider_can/driver/baudrate: 125000
provider_can/driver/device_id: 1
provider_can/driver/unique_id: 1
provider_can/driver/channel: 0
provider_can/driver/usb_device: "KVaser"
